sources:
  - url: https://xrobot-org.github.io/xrobot-modules/index.yaml
    priority: 0
  - url: https://xiaoshuaijie.github.io/jie-modules/index.yaml
    priority: 1
  - url: https://qdu-robomaster.github.io/qdu-future-modules/index.yaml
    priority: 0
